http://localhost:3000

###Login Route
POST http://localhost:3000/auth/login

###Register Route
POST http://localhost:3000/auth/register

###Refresh token Route
POST http://localhost:3000/auth/refresh-token

###Logout Route
DELETE http://localhost:3000/auth/logout



#####################
GET http://localhost:3000/users


####
//testing our error handling
GET http://localhost:3000/k
###
GET http://localhost:3000/users/63a78a580ea068ea093ce746


#######
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstname" : "Rajesh",
    "lastname" : "Koothrapali",
    "email": "rajeshK@gmail.com",
    "address" : "Fictionstrasse 12",
    "password" : "raj23484@@",
    "PLZ" : "36039"
}


####
POST http://localhost:3000/users/auth/login
Content-Type: application/json

{
    "email" : "rajeshK@gmail.com",
    "password" : "raj23484@@"
}


####
DELETE  http://localhost:3000/users/63a78cac0ea068ea093ce748


######
PATCH   http://localhost:3000/users/63a78a580ea068ea093ce746
Content-Type: application/json

{
    "email" : "eddiej@gmail.com",
    "PLZ" : "36037"
}

////////////////////// restaurant calls
#####

GET http://localhost:3000/restaurants

######
POST http://localhost:3000/restaurants
Content-Type: application/json

{
    "name" : "Kaptain Pizza",
    "address" : "Aschernbergplatz 15",
    "email" : "kaptainpizza@yahoo.com",
    "PLZ" : "36039",
    "longitude" : "-80.5748348839",
    "latitude" : "30.33487484834"
}
####
DELETE http://localhost:3000/restaurants/63a8bc529cc87f0e078b531a

#########
GET http://localhost:3000/restaurants/638376f4905e75b1fd0a586c

####### 
PATCH   http://localhost:3000/restaurants/63837f64199eb8289afb1c42
Content-Type: application/json

{
    "name" : "Mama Mia",
    "email" : "mamamia@gmail.com"
}


////////////////// reservation calls
####
GET http://localhost:3000/reservations

######
POST http://localhost:3000/reservations
Content-Type: application/json

{
    "restaurant_id" : "638376f4905e75b1fd0a586c",
    "user_id" : "63a848f375225f0eaeff820a",
    "table_id" : "CB78",
    "reservation_date" : "2023-01-05",
    "reservation_time" : "20:30"
}

######## Get reservation from a specific user
GET http://localhost:3000/reservations/user/63a848f375225f0eaeff820a

########
GET http://localhost:3000/reservations/restaurant/638376f4905e75b1fd0a586c


####
DELETE http://localhost:3000/reservations/6382a4d10b770db9ebcbc28e

/////////////////////// menu calls

#########
GET http://localhost:3000/menus/

#############
GET http://localhost:3000/menus/nachspeise/63837f64199eb8289afb1c42
